export const data = {
  countries: [
    { code: "IN", name: "India" },
    { code: "US", name: "United States" },
    { code: "CA", name: "Canada" },
  ],

  states: {
    IN: ["Gujarat", "Rajsthan"],
    US: ["Alabama", "Alaska"],
    CA: ["Ontario", "Quebec"],
  },

  citys: {
    Gujarat: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Gandhinagar",
      "Bhavnagar",
      "Jamnagar",
      "Anand",
      "Bhuj",
      "Porbandar",
    ],
    Rajsthan: [
      "Jaipur",
      "Udaipur",
      "Jodhpur",
      "Ajmer",
      "Kota",
      "Bikaner",
      "Alwar",
      "Mount Abu",
      "Bharatpur",
      "Sikar",
    ],
    Alabama: ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
    Alaska: ["Anchorage", "Juneau", "Fairbanks", "Wasilla", "Sitka"],
    Ontario: [
      "Toronto",
      "Ottawa",
      "Mississauga",
      "Brampton",
      "Hamilton",
      "London",
      "Markham",
      "Vaughan",
      "Kitchener",
      "Windsor",
    ],
    Quebec: [
      "Montreal",
      "Quebec City",
      "Laval",
      "Gatineau",
      "Longueuil",
      "Sherbrooke",
      "Saguenay",
      "Trois-Rivières",
      "Terrebonne",
      "Saint-Jean-sur-Richelieu",
    ],
  },
};

export const hobbies = [
  "Cricket",
  "Reading",
  "Traveling",
  "Cooking",
  "Gardening",
  "Dancing",
  "Hiking",
  "Gaming",
  "Editing",
  "Fitness",
  "Meditation",
];
